name: 'extract metadata from git state'
description: 'extracts metadata like version, nightly etc. from github context, and git information'

outputs:
  version:
    description: "version"
    value: ${{ steps.metadata.outputs.version }}

  is_nightly:
    description: "is_nightly"
    value: ${{ steps.metadata.outputs.is_nightly }}

  short_sha:
    description: "short_sha"
    value: ${{ steps.metadata.outputs.short_sha }}

  sha:
    description: "sha"
    value: ${{ steps.metadata.outputs.sha }}

  platform:
    description: "platform info like linux/amd64, linux/arm64 etc."
    value: ${{ steps.metadata.outputs.platform }}

runs:
  using: 'composite'
  steps:
    - name: Extract Metadata
      shell: bash
      id: metadata
      run: |+
        echo "short_sha=$(git rev-parse --short HEAD)" | tee -a $GITHUB_OUTPUT
        echo "sha=${{ github.sha }}" | tee -a $GITHUB_OUTPUT

        branch="${{ github.ref }}"
        version=""
        is_nightly=false

        if [[ "$branch" =~ ^refs/heads/* ]]; then
          is_nightly=true
          version="${branch#refs/heads/}"
          
          if [[ $version == release-* ]]; then
            version=${version#release-}
          fi

          if [[ $version != *-nightly ]]; then
            version="${version}-nightly"
          fi
        fi

        if [[ "$branch" =~ ^refs/tags/* ]]; then
          version="${branch#refs/tags/}"
          is_nightly=false
        fi

        echo "version=$version" | tee -a $GITHUB_OUTPUT
        echo "is_nightly=$is_nightly" | tee -a $GITHUB_OUTPUT

        arch=$(uname -m)
        case "$arch" in
          x86_64) arch="amd64" ;;
          aarch64) arch="arm64" ;;
          armv7l) arch="arm" ;;
          i386) arch="386" ;;
        esac

        echo "platform=$(uname -s | tr '[:upper:]' '[:lower:]')/$arch" | tee -a $GITHUB_OUTPUT
