name: 'extract metadata from git state'
description: 'extracts metadata like version, nightly etc. from github context, and git information'

outputs:
  version:
    description: "version"
    value: ${{ steps.metadata.outputs.version }}

  semver:
    description: "semver"
    value: ${{ steps.metadata.outputs.semver }}

  is_nightly:
    description: "is_nightly"
    value: ${{ steps.metadata.outputs.is_nightly }}

  short_sha:
    description: "short_sha"
    value: ${{ steps.metadata.outputs.short_sha }}

  sha:
    description: "sha"
    value: ${{ steps.metadata.outputs.sha }}

  platform:
    description: "platform info like linux/amd64, linux/arm64 etc."
    value: ${{ steps.metadata.outputs.platform }}

runs:
  using: 'composite'
  steps:
    - name: Extract Metadata
      shell: bash
      id: metadata
      run: |+
        echo "short_sha=$(git rev-parse --short HEAD)" | tee -a $GITHUB_OUTPUT
        echo "sha=${{ github.sha }}" | tee -a $GITHUB_OUTPUT

        branch="${{ github.ref }}"
        semver=""
        is_nightly=false

        if [[ "$branch" =~ ^refs/heads/* ]]; then
          is_nightly=true
          semver="${branch#refs/heads/}"
          
          if [[ $semver != *-nightly ]]; then
            semver="${semver}-nightly"
          fi

          semver="0.0.0-${semver}"
        fi

        if [[ "$branch" =~ ^refs/tags/* ]]; then
          is_nightly=false
          semver="${branch#refs/tags/}"
        fi

        if [[ $semver == release-* ]]; then
          semver=${semver#release-}
        fi

        if [[ $semver == v* ]]; then
          semver="${semver#v}"
        fi

        echo "semver=$semver" | tee -a $GITHUB_OUTPUT
        echo "version=v${semver}" | tee -a $GITHUB_OUTPUT
        echo "is_nightly=$is_nightly" | tee -a $GITHUB_OUTPUT

        arch=$(uname -m)
        case "$arch" in
          x86_64) arch="amd64" ;;
          aarch64) arch="arm64" ;;
          armv7l) arch="arm" ;;
          i386) arch="386" ;;
        esac

        echo "platform=$(uname -s | tr '[:upper:]' '[:lower:]')/$arch" | tee -a $GITHUB_OUTPUT
