name: 'extract metadata from git state'
description: 'extracts metadata like version, nightly etc. from github context, and git information'

runs:
  using: 'composite'
  steps:
    - name: Extract Metadata
      shell: bash
      run: |+
        branch="${{ github.ref }}"

        version=""
        is_nightly=false

        if [[ "$branch" =~ ^refs/heads/* ]]; then
          is_nightly=true
          version="${branch#refs/heads/}"
          
          if [[ $version == release-* ]]; then
            version=${version#release-}
          fi

          if [[ $version != *-nightly ]]; then
            version="${version}-nightly"
          fi
        fi

        if [[ "$branch" =~ ^refs/tags/* ]]; then
          version="${branch#refs/tag/}"
          is_nightly=false
        fi

        echo "version=$version" | tee -a $GITHUB_OUTPUT
        echo "short_sha=$(git rev-parse --short HEAD)" | tee -a $GITHUB_OUTPUT
        echo "sha=${{ github.sha }}" | tee -a $GITHUB_OUTPUT
        echo "is_nightly=$is_nightly" | tee -a $GITHUB_OUTPUT
