name: github-release-create
description: 'creates a github release based on release name'

inputs:
  name:
    description:  "Github Release Name"
    type: string
    required: true

  github_token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    type: string
    required: true

  pre_release:
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
    - name: create github release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        version: ${{ inputs.name }}
        pre_release: ${{ inputs.pre_release }}
      run: |+
        if gh release list -R ${{github.repository}} --json name | jq -e --arg val "${version}" 'map_values(.name) | index($val) != null'; then
          # means already exists
          if $pre_release; then
            gh release delete ${version} -y --cleanup-tag -R ${{ github.repository }}
          else
            echo "Release ($version) already exists, reusing it"
            exit 0
          fi
        fi

        args=("--generate-notes")
        if $pre_release; then
          args+=("--prerelease")
        fi

        gh release create "${version}" -R "${{ github.repository }}" ${args[@]}
