inputs:
  docker_registry: 
    description: "Docker registry"
    default: "ghcr.io"

  docker_username: 
    description: "Docker username"
    required: true

  docker_password: 
    description: "Docker username"
    required: true

  qemu:
    desciprtion: "Should Enable QEMU"
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      if: ${{ fromJSON(inputs.qemu) }}
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
